; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = pico

[env]
framework = arduino
lib_deps = 
	https://github.com/micro-ROS/micro_ros_platformio
    https://github.com/end2endzone/AnyRtttl
	sparkfun/SparkFun 9DoF IMU Breakout - ICM 20948 - Arduino Library@^1.2.12

lib_archive = false
board_microros_distro = humble
board_microros_transport = serial
; build_src_filter = +<calibration.cpp>

; Enable Sensor Fusion on the IMU
build_flags = 
	-DICM_20948_USE_DMP


[env:pico]
; platform = raspberrypi
platform = https://github.com/maxgerhardt/platform-raspberrypi.git

; platform_packages =
;   toolchain-gccarmnoneeabi@~1.90301.0/
;   framework-arduinopico@https://github.com/earlephilhower/arduino-pico.git@#3.9.4
; platform = https://github.com/platformio/platform-raspberrypi.git
; platform = platformio/raspberrypi@^1.14.0
board = pico
board_build.core = earlephilhower

board_build.mcu = rp2040
; change MCU frequency
board_build.f_cpu = 133000000L
; board_build.filesystem_size = 0.5m


; OPTION 1: Use the picoprobe as upload and debug tool
; note: newer PicoProbe firmwares emulate a CMSIS-DAP, so you
; use “cmsis-dap” as upload_protocol and debug_tool.
upload_protocol = cmsis-dap
debug_tool = cmsis-dap
; debug_speed = 30000
debug_speed = 5000
upload_speed = 5000

; debug_speed = 5000
; upload_protocol = picoprobe
; debug_tool = picoprobe

; OPTION 2: Use the picotool uploader
; upload_protocol = picotool

; OPTION 3: Use the official Raspberry Pi Pico SDK uploader
; upload_port = /mnt/deepdrive_micro
; upload_protocol = mbed

monitor_speed = 115200

build_type = debug

; Examples 1: disable initial breakpoint
debug_init_break =

; Examples 2: temporary stop at ``void loop()`` function
; debug_init_break = tbreak loop

; Examples 3: stop in main.cpp at line 13
; debug_init_break = break main.cpp:13

; Examples 4: temporary stop at ``void Reset_Handler(void)``
; debug_init_break = tbreak Reset_Handler

; debug_init_break = tbreak setup

; debug_extra_cmds = 
; 	continue

; debug_extra_cmds =
;   break main.cpp:13
;   break foo.cpp:100
;   source .gdbinit

; build_flags = -DPIO_FRAMEWORK_ARDUINO_ENABLE_BLUETOOTH

; ; Enable Stack Protector
; build_flags = -fstack-protector

; ; Enable Exceptions
; build_flags = -DPIO_FRAMEWORK_ARDUINO_ENABLE_EXCEPTIONS
	


; ; Debug level: Core
; build_flags = -DDEBUG_RP2040_CORE
; ; Debug level: SPI
; build_flags = -DDEBUG_RP2040_SPI
; ; Debug level: Wire
; build_flags = -DDEBUG_RP2040_WIRE
; ; Debug level: All
; build_flags = -DDEBUG_RP2040_WIRE -DDEBUG_RP2040_SPI -DDEBUG_RP2040_CORE
; ; Debug level: NDEBUG
; build_flags = -DNDEBUG

; ; example: Debug port on serial 2 and all debug output
; build_flags = -DDEBUG_RP2040_WIRE -DDEBUG_RP2040_SPI -DDEBUG_RP2040_CORE -DDEBUG_RP2040_PORT=Serial2
; ; equivalent to above
; build_flags =
;    -DDEBUG_RP2040_WIRE
;    -DDEBUG_RP2040_SPI
;    -DDEBUG_RP2040_CORE
;    -DDEBUG_RP2040_PORT=Serial2